import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY } from "./config.js";
const sb=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY),PRICE=50,$=s=>document.querySelector(s);
const money=v=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN"}).format(v);
function addAttendee(){const row=document.createElement("div");row.className="attendee-row";row.innerHTML='<input class="attendee-name" placeholder="Nombre completo del asistente" required><button type="button" class="btn danger small remove-attendee">Eliminar</button>';row.querySelector(".remove-attendee").onclick=()=>{row.remove();updateTotal()};$("#attendees").appendChild(row);updateTotal()}
function updateTotal(){const n=document.querySelectorAll(".attendee-row").length;$("#attendeeCount").textContent=n;$("#amountTotal").textContent=money(n*PRICE)}
$("#addAttendee").onclick=addAttendee;addAttendee();
$("#reservationForm").addEventListener("submit",async e=>{e.preventDefault();const personas=[...document.querySelectorAll(".attendee-name")].map(x=>x.value.trim()).filter(Boolean);if(!personas.length)return alert("Agrega al menos un asistente.");const ref=new URLSearchParams(location.search).get("ref")||"";const {data,error}=await sb.rpc("crear_reservacion_publica",{p_contacto_nombre:$("#contactName").value.trim(),p_contacto_telefono:$("#contactPhone").value.trim(),p_contacto_email:$("#contactEmail").value.trim()||null,p_invitado_por:ref,p_personas:personas});if(error)return alert(error.message);const r=Array.isArray(data)?data[0]:data;sessionStorage.setItem("fiesta15_token",r.public_token);showReservation(r)});
async function showReservation(r){$("#reservationForm").classList.add("hidden");const b=await fetch("./datos_bancarios.json").then(x=>x.json()).catch(()=>({}));const box=$("#reservationResult");box.classList.remove("hidden");box.innerHTML=`<div class="flag-big">🎟️</div><h2>Reservación creada</h2><div class="receipt"><div><span>Folio</span><strong>${r.folio}</strong></div><div><span>Boletos</span><strong>${r.cantidad}</strong></div><div><span>Precio unitario</span><strong>${money(PRICE)}</strong></div><div><span>Total</span><strong>${money(r.total)}</strong></div><div><span>Estado</span><strong>PENDIENTE DE PAGO</strong></div></div><div class="bank-box"><h3>Datos para transferencia</h3><p><strong>Banco:</strong> ${b.banco||"PENDIENTE"}</p><p><strong>Beneficiario:</strong> ${b.beneficiario||"PENDIENTE"}</p><p><strong>CLABE / Cuenta:</strong> ${b.clabe_cuenta||"PENDIENTE"}</p><p><strong>Concepto:</strong> ${r.folio}</p></div><h3>Subir comprobante</h3><input id="proofFile" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"><button id="uploadProof" class="btn primary full">Enviar comprobante</button><a class="btn secondary full link-btn" href="./estado.html?token=${encodeURIComponent(r.public_token)}">Consultar estado</a>`;$("#uploadProof").onclick=()=>uploadProof(r.public_token)}
async function uploadProof(token){const f=$("#proofFile").files[0];if(!f)return alert("Selecciona una imagen o PDF.");if(f.size>8388608)return alert("Máximo 8 MB.");const ext=(f.name.split(".").pop()||"bin").toLowerCase(),path=`${token}/${crypto.randomUUID()}.${ext}`;const {error:upErr}=await sb.storage.from("comprobantes-pago").upload(path,f,{upsert:false,contentType:f.type});if(upErr)return alert(upErr.message);const {error}=await sb.rpc("registrar_comprobante_publico",{p_token:token,p_path:path});if(error)return alert(error.message);alert("Comprobante enviado. Quedó pendiente de validación.");location.href=`./estado.html?token=${encodeURIComponent(token)}`}
