-- MIGRACIÓN V2. Ejecutar después de supabase_schema.sql
create table if not exists public.reservaciones (id uuid primary key default gen_random_uuid(),folio text not null unique,public_token uuid not null unique default gen_random_uuid(),contacto_nombre text not null,contacto_telefono text not null,contacto_email text,invitado_por text not null default '',cantidad integer not null check(cantidad>0 and cantidad<=30),precio_unitario numeric(10,2) not null default 50,total numeric(10,2) not null,estado text not null default 'PENDIENTE_PAGO' check(estado in('PENDIENTE_PAGO','COMPROBANTE_ENVIADO','PAGADO','RECHAZADO')),comprobante_path text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.reservacion_personas(id uuid primary key default gen_random_uuid(),reservacion_id uuid not null references public.reservaciones(id) on delete cascade,nombre text not null,orden integer not null,invitado_id uuid null references public.invitados(id) on delete set null,created_at timestamptz not null default now(),unique(reservacion_id,orden));
alter table public.reservaciones enable row level security;alter table public.reservacion_personas enable row level security;
drop policy if exists admin_reservaciones on public.reservaciones;create policy admin_reservaciones on public.reservaciones for all to authenticated using(true) with check(true);
drop policy if exists admin_reservacion_personas on public.reservacion_personas;create policy admin_reservacion_personas on public.reservacion_personas for all to authenticated using(true) with check(true);
grant select,update,delete on public.reservaciones to authenticated;grant select,update,delete on public.reservacion_personas to authenticated;
create sequence if not exists public.folio_reservacion_seq start 1;
create or replace function public.crear_reservacion_publica(p_contacto_nombre text,p_contacto_telefono text,p_contacto_email text,p_invitado_por text,p_personas text[]) returns table(folio text,public_token uuid,cantidad integer,total numeric) language plpgsql security definer set search_path='' as $$ declare v_id uuid;v_folio text;v_token uuid;v_cantidad integer;v_total numeric(10,2);i integer;begin v_cantidad:=coalesce(array_length(p_personas,1),0);if v_cantidad<1 or v_cantidad>30 then raise exception 'Entre 1 y 30 asistentes';end if;v_folio:='F15-2026-'||lpad(nextval('public.folio_reservacion_seq')::text,5,'0');v_token:=gen_random_uuid();v_total:=v_cantidad*50;insert into public.reservaciones(folio,public_token,contacto_nombre,contacto_telefono,contacto_email,invitado_por,cantidad,precio_unitario,total) values(v_folio,v_token,trim(p_contacto_nombre),trim(p_contacto_telefono),nullif(trim(p_contacto_email),''),coalesce(trim(p_invitado_por),''),v_cantidad,50,v_total) returning id into v_id;for i in 1..v_cantidad loop insert into public.reservacion_personas(reservacion_id,nombre,orden) values(v_id,trim(p_personas[i]),i);end loop;return query select v_folio,v_token,v_cantidad,v_total;end $$;
revoke all on function public.crear_reservacion_publica(text,text,text,text,text[]) from public;grant execute on function public.crear_reservacion_publica(text,text,text,text,text[]) to anon,authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('comprobantes-pago','comprobantes-pago',false,8388608,array['image/jpeg','image/png','image/webp','application/pdf']) on conflict(id) do update set public=false,file_size_limit=8388608,allowed_mime_types=array['image/jpeg','image/png','image/webp','application/pdf'];
drop policy if exists public_upload_comprobante on storage.objects;create policy public_upload_comprobante on storage.objects for insert to anon,authenticated with check(bucket_id='comprobantes-pago' and exists(select 1 from public.reservaciones r where r.public_token::text=(storage.foldername(name))[1] and r.estado in('PENDIENTE_PAGO','RECHAZADO')));
drop policy if exists admin_read_comprobantes on storage.objects;create policy admin_read_comprobantes on storage.objects for select to authenticated using(bucket_id='comprobantes-pago');
create or replace function public.registrar_comprobante_publico(p_token uuid,p_path text) returns void language plpgsql security definer set search_path='' as $$ begin if split_part(p_path,'/',1)<>p_token::text then raise exception 'Ruta inválida';end if;update public.reservaciones set comprobante_path=p_path,estado='COMPROBANTE_ENVIADO',updated_at=now() where public_token=p_token and estado in('PENDIENTE_PAGO','RECHAZADO');if not found then raise exception 'Reservación no disponible';end if;end $$;revoke all on function public.registrar_comprobante_publico(uuid,text) from public;grant execute on function public.registrar_comprobante_publico(uuid,text) to anon,authenticated;
create or replace function public.consultar_reservacion_publica(p_token uuid) returns jsonb language plpgsql security definer set search_path='' as $$ declare r public.reservaciones%rowtype;tickets jsonb:='[]'::jsonb;begin select * into r from public.reservaciones where public_token=p_token;if not found then return null;end if;if r.estado='PAGADO' then select coalesce(jsonb_agg(jsonb_build_object('nombre',i.nombre,'codigo',i.codigo) order by rp.orden),'[]'::jsonb) into tickets from public.reservacion_personas rp join public.invitados i on i.id=rp.invitado_id where rp.reservacion_id=r.id;end if;return jsonb_build_object('folio',r.folio,'contacto_nombre',r.contacto_nombre,'cantidad',r.cantidad,'total',r.total,'estado',r.estado,'boletos',tickets);end $$;revoke all on function public.consultar_reservacion_publica(uuid) from public;grant execute on function public.consultar_reservacion_publica(uuid) to anon,authenticated;
create or replace function public.aprobar_reservacion(p_reservacion_id uuid) returns void language plpgsql security definer set search_path='' as $$ declare r public.reservaciones%rowtype;p record;v_inv_id uuid;v_codigo text;begin if auth.uid() is null then raise exception 'No autenticado';end if;select * into r from public.reservaciones where id=p_reservacion_id for update;if not found then raise exception 'Reservación no encontrada';end if;if r.estado='PAGADO' then return;end if;if r.estado<>'COMPROBANTE_ENVIADO' then raise exception 'Sin comprobante pendiente';end if;for p in select * from public.reservacion_personas where reservacion_id=r.id order by orden loop if p.invitado_id is null then v_codigo:='F15-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,14));insert into public.invitados(codigo,nombre,apellido,invitado_por,cuenta_pago,pagado) values(v_codigo,p.nombre,'',r.invitado_por,r.folio,true) returning id into v_inv_id;update public.reservacion_personas set invitado_id=v_inv_id where id=p.id;end if;end loop;update public.reservaciones set estado='PAGADO',updated_at=now() where id=r.id;end $$;revoke all on function public.aprobar_reservacion(uuid) from public,anon;grant execute on function public.aprobar_reservacion(uuid) to authenticated;
create or replace function public.rechazar_reservacion(p_reservacion_id uuid) returns void language plpgsql security definer set search_path='' as $$ begin if auth.uid() is null then raise exception 'No autenticado';end if;update public.reservaciones set estado='RECHAZADO',updated_at=now() where id=p_reservacion_id and estado='COMPROBANTE_ENVIADO';end $$;revoke all on function public.rechazar_reservacion(uuid) from public,anon;grant execute on function public.rechazar_reservacion(uuid) to authenticated;
do $$ begin alter publication supabase_realtime add table public.reservaciones;exception when duplicate_object then null;end $$;
